# Generated by Django 3.0 on 2020-08-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caferinocalendar', '0003_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
