# Generated by Django 3.1.1 on 2020-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='', help_text='Recommended image size: 324x175.', upload_to='static/'),
            preserve_default=False,
        ),
    ]
