# Generated by Django 3.1 on 2020-08-29 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/')),
                ('image1', models.ImageField(blank=True, default='', upload_to='static/')),
                ('image2', models.ImageField(blank=True, default='', upload_to='static/')),
                ('image3', models.ImageField(blank=True, default='', upload_to='static/')),
                ('image4', models.ImageField(blank=True, default='', upload_to='static/')),
                ('image5', models.ImageField(blank=True, default='', upload_to='static/')),
                ('image6', models.ImageField(blank=True, default='', upload_to='static/')),
                ('category', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ateliere.event')),
            ],
        ),
    ]
