# Generated by Django 3.1.1 on 2020-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(help_text='Recommended image size: 324x175.', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image1',
            field=models.ImageField(blank=True, default='', help_text='Recommended image size: 324x175.', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, default='', help_text='Recommended image size: 324x175.', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image3',
            field=models.ImageField(blank=True, default='', help_text='Recommended image size: 324x175.', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image4',
            field=models.ImageField(blank=True, default='', help_text='Recommended image size: 324x175.', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image5',
            field=models.ImageField(blank=True, default='', help_text='Recommended image size: 324x175.', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image6',
            field=models.ImageField(blank=True, default='', help_text='Recommended image size: 324x175.', upload_to='static/'),
        ),
    ]
