# Generated by Django 3.0 on 2020-08-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='pic_folder/'),
            preserve_default=False,
        ),
    ]
