# Generated by Django 3.1.1 on 2021-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0002_auto_20200912_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='childAge',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='childName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
