# Generated by Django 3.0 on 2020-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0002_auto_20200825_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
