# Generated by Django 3.1.1 on 2021-09-19 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0003_auto_20210311_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ateliere.event')),
            ],
        ),
    ]
