# Generated by Django 3.0 on 2020-08-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0003_auto_20200825_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
