# Generated by Django 3.0 on 2020-08-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0004_auto_20200825_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(height_field=226, upload_to='static/', width_field=300),
        ),
    ]
