# Generated by Django 3.1.1 on 2021-09-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0004_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
