# Generated by Django 3.1.1 on 2021-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0005_participation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='start_date',
            field=models.CharField(max_length=200),
        ),
    ]
