# Generated by Django 3.0 on 2020-08-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0005_auto_20200826_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_image', models.ImageField(upload_to='static/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ateliere.Event')),
            ],
        ),
    ]
