# Generated by Django 3.0 on 2020-08-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0006_auto_20200826_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image1',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image3',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image4',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image5',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image6',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.DeleteModel(
            name='EventImages',
        ),
    ]
