# Generated by Django 3.1.1 on 2022-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliere', '0006_auto_20210924_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Parcul Circului', 'Parcul Circului'), ('Aurel Vlaicu', 'Aurel Vlaicu')], default='Parcul Circului', max_length=20),
        ),
    ]
