# Generated by Django 3.1 on 2020-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
