# Generated by Django 3.0 on 2020-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
