# Generated by Django 3.0 on 2020-08-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfhomepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprojects',
            name='image',
            field=models.ImageField(default='', upload_to='static/'),
            preserve_default=False,
        ),
    ]
