# Generated by Django 3.0 on 2020-08-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfhomepage', '0002_socialprojects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprojects',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='socialprojects',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='socialprojects',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
